language: node_js
node_js
  - "4.1"

install:
  - npm install grunt-cli -g
  - npm install --save-dev

script:
  - grunt deploy

env:
  global:
    - GH_REF: "tntcrowd/educast-help"
    - secure: "oDZxNAnpSNnqi2cK4LzDWXS2bc7DRO4HXrVWZWozg4qNGRNL7CICYKd12jdQOJ0ht5VmpTG9nRqCQQunYikAmUBuvD0CWQsBKWlcuRJS5EiIxPlejHgRpRhsVIojAE8GULT266Y9CPCLvWGrJiDiaEY2+wpCmuMVrt00x23cIKbuSHxFqtNgLhxun8h0RUI1ls/RdTDo5tTNBboiAc+p4uKmyu6DHtYVeKadCX3D3r4/IBxkr4X6pB4fOJzn/Ub2MZOSC/1Cz7bntEgImkfFApD75CAei1mD3ez5HA/6BbVbkFq2KiZbcCl2Q5rF54IKm+Vdxvq7Vzdo7EWJUo9Uf9a/VB0UE5IZVjhWdrJD0O6x0LXakDlQ5wpFsZSLvRvxHb8eet3104JYcjkTyKOiPffRrgoGMyjZtQfFiRT6ihkENqdVmatluyYN25255HIVpDFEyyAhH1Q9YPkSRo52D0z9mBHmUzFZeAYOx23tD+br5HjL0XETPJgQQM8T/rFqBCjVqNQI7pTM4p0k6IF/nPUUiP5l9yeukaC/r+ovAMkIuXmHN1brvgNbkvawxU0ODSaA5fpdgHd456UHd2tNpxLLwJ02ylc1QnZUWMOml0dDEb7ZhNLXUMDOlsfJhW9u/nmVmg8qve4+qUe+fLEVK2daclsDx7fk1O946XZevbA="