branches:
  only:
    - master
    - gh-pages
language: node_js
node_js:
- '4.2.6'
install:
- npm install grunt-cli -g
- npm install --save-dev
script:
- grunt deploy
env:
  global:
  - GH_REF: tntcrowd/educast-help
  - GH_EMAIL: devmaster@tntcrowd.com
  - GH_USERNAME: TNTcrowd
  - secure: fRCvwl8Iqv3ZO8Zf6Gg6I/SgP/MCAWPkCMFsWBx2kmBZQi1fE0ADlo37FLqLcvbAZTBQfyZHQ98H1UBe6TEXucfpqONC/Yjmso2NWx8JOICk0PotMZ94uVGmw9qpAkibo2JXdWKzCY0/fFJ6FHwb+IMExomYIe7PIvn4s/CZ28YpTj4VSeZJtlYiolqF36PYltVGzEWpBAY34lmS/EWkW8FvabAOAwlyR60Zm2dfTzfocLWke3ZkhdCXKIOjNjUK1Z77jfgDI8nGA683hkE+DxLPRzIXIUP58e+pg1iPN1clz/+GSQEOEKM/Hj0+sCyLN5cj2eWFnysTQIdIhPNF3SsgH0GSkd8fgFAyVTdd6I+ZE50lbFrUdYTawNSWWfMfIKOshMjjgGb+3geemA8elIGRgEEdBmoSWSuh44ETgCwzSM9b1b9P5YOfHJvMglxB+wTlJb4ZJckTXt8/txlGmasmhLDtjTI4fAk32sSnUVFCfMGLMF6zfyKsyAnHfNRGUR5dfQymTnSAdRCH2BDwZVyI1FTtLOliPhn6BeCL0jSu3Z2m+DofjEOwusMF185Hm19Y3sguGNJ0Up4UmkbLT/XZxR7GntSg+tRorRXW3uvSgkHiA1oP0cXNMIOrbTMY47KbJV/1r2bI4esigKGo4iquQndgeF2CLrtgmM99fwY=
