branches:
  only:
    - master
    - gh-pages
language: node_js
node_js:
- '4.2.6'
install:
- npm install grunt-cli -g
- npm install --save-dev
script:
- grunt deploy
env:
  global:
  - GH_REF: tntcrowd/educast-help
  - GH_EMAIL: devmaster@tntcrowd.com
  - GH_USERNAME: TNTcrowd
  - secure: "qGIca/+Stz54VNH1NGvwdSqcKwz8fo4NoKpUObx0uY8HcZHaZUTeJDdeY5PQeETALXwMu+ao/Hrdv/rmBejHIEcmKuRQN3NLt7fPURnGSE7gF6ZaHPDX1J76CaOvf0Wn03hiWbbjy7q/v/pamrNJOYTFw3PjGIC7ZlJ/2oMhwdInkvqHY36ScGwOL0txFqy+Fd9u6aaYVzH/jNvY3sOsBAUy8+vGavsG/nFL6IQiqdJELaO7LZt7q11LzMErdylj8RbY4utMYEGEu8nTUSqh9cMBS/ZPuY6pMJp67AlG6Bn6E/b62vSyoRaW5CK13WxvFj4kBc47a8Khamffaffts8zB98Vmd0VyXtTEOBMcSy6VW4yVo2uFJgcEiIyG5MetfzY0N3g82lEkTfb0ZFqLuqu+zLtfxoWHz+aS3vB4IW9XaLaR0J0fnqK5e9u3PCyTC+uQq0oY4vEeCu463cquFbRzoPhMeP2NrGqqFPmIJLLW3EmHxgQrCiCkM/qxsOZpemkcI2O+OJGu2I9YDgY5i9o4EVUKMpsmkFIuOXyNfteSsAXZht3BMVuoD6na0cVOPoK1cwbkH2L9Ctk0NHfu3fkcoLoOkNsHc87ltlvTpeif59AeQAzG89u5MP4/0YtLaKXgNtxK0ddITe4H1bXDbEcWBeeG8c/mn8Gok57reU4="
notifications:
  slack: tntcrowd:rPkJUJmXaQZxd1YuwNpZIFrS
